[package]
name = "heroes-of-camelot"
version = "0.1.0"
edition = "2024"


[features]
local-data = []

[dependencies]
macroquad = "0.4.14"
uuid = { version = "1.16.0", features = ["v4"] }
async-trait = "0.1.88"
slug = "0.1"